"""add account status column

Revision ID: 95bb619cdc1d
Revises: 2b3db33e546a
Create Date: 2026-08-14 12:10:17.659183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95bb619cdc1d'
down_revision: Union[str, Sequence[str], None] = '2b3db33e546a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status', sa.String(), nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'status')
    # ### end Alembic commands ###